version: 2.1

orbs:
  android: circleci/android@2.2.0

jobs:
  build-and-test:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1

    steps:
      - checkout
      - run:
          command: cp ./.circleci/local.properties.ci local.properties
      - android/run-tests:
          test-command: ./gradlew lint testDebug --continue
      - android/create-avd:
          avd-name: myavd
          install: true
          system-image: system-images;android-29;default;x86
      - android/start-emulator:
          avd-name: myavd
          no-window: true
          restore-gradle-cache-prefix: v1a
      - android/save-gradle-cache:
          cache-prefix: v1a

workflows:
  test:
    jobs:
      - build-and-test

# ■ memo ■
# チェックコマンド： circleci config validate
#
# ■ 特に参考にしたサイト ■
# Android プロジェクトの継続的インテグレーション
# https://circleci.com/ja/blog/building-android-on-circleci/
# 3年の運用で編み出した CircleCI 超設計大全
# https://qiita.com/dodonki1223/items/98dbdac6f31f9b486ecf
