version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4

jobs:
  build-and-test:
    docker:
      - image: cimg/android:2023.04
    steps:
      - checkout
      - run:
          name: copy local.properties
          command: cp ./.circleci/local.properties.ci local.properties
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}
      - run: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}

      - run:
          command: sudo gem install bundler:2.4.12
      - run:
          command: bundle install --path vendor/bundle
      - run:
          name: ktlint-check
          command: ./gradlew --continue ktlintCheck

      - run:
          name: test
          command: ./gradlew testDebug --stacktrace

      - run:
          name: jacoco-report
          command: ./gradlew jacocoTestReport

      - run:
          name: merge-jacoco
          command: ./gradlew mergeJacoco

      - run:
          name: run-danger-file
          command: bundle exec danger --verbose

      - codecov/upload

workflows:
  test:
    jobs:
      - build-and-test

# ■ memo ■
# チェックコマンド： circleci config validate
#
# ■ 特に参考にしたサイト ■
# Android プロジェクトの継続的インテグレーション
# https://circleci.com/ja/blog/building-android-on-circleci/
# 3年の運用で編み出した CircleCI 超設計大全
# https://qiita.com/dodonki1223/items/98dbdac6f31f9b486ecf
