version: 2.1

orbs:
  android: circleci/android@2.2.0

jobs:
  build-and-test:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2023.4.2

    steps:
      - checkout
      - run:
          command: cp ./.circleci/local.properties.ci local.properties
      - android/run-tests:
          test-command: ./gradlew lint testDebug --continue
      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedDebugAndroidTest
          system-image: system-images;android-29;default;x86
      - android/save-gradle-cache:
          cache-prefix: v1

workflows:
  test:
    jobs:
      - build-and-test

# ■ memo ■
# チェックコマンド： circleci config validate